# -*- coding: utf-8 -*-
"""Day1InPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/imksav/4d1cba4156adb3cb305a895d8fd7619a/day1inpython.ipynb
"""


fName = "Keshav"
space = " "
lname = "Bhandari"
fullName = fName+space+lname  # to concatate
print(fullName)
print(fName[3])  # to print the character of given place value
print(len(fName))  # to get the length of string data
print(fullName[2:6])  # include the begining and exclude the ending place value
data1 = "     Hello       Guys!"
# newData1 = strip(data1)
newData1 = data1.strip()  # strip() remove any whitespaces at the begining
print(newData1)
print(fullName.lower())  # lower() make all the letters in lowercase
print(fullName.upper())  # upper() make all the letters in uppercase
print(data1.replace("H", "#H"))  # to replace the any letters in a string
print(fullName.split(" "))
skills = "Teaching,Tutoring,Dancing,Singing,Cricket Playing,Programming,Documentation,Photoshop,Event Management,App Development,Software Development,Web Development"
print(skills.split(","))

x = str(3)    # x will be '3'
print(x)
print(type(x))
y = int(3)    # y will be 3
print(y)
print(type(y))
z = float(3)  # z will be 3.0
print(z)
print(type(z))

x = 23.56
y = 12
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x % y)

x = 5
y = 10
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x % y)
print(type(x))  # to get the which type of data is assigned to the variable

print("Hello World!")
