# -*- coding: utf-8 -*-
"""Day1InPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CEmQH77IUdWSUzxcleI2yHqnpVwpeopn
"""

a, b = 0,1
while a<100:
  print(a, end=",")
  a,b = b, a+b

"""## `**First Step towards Programming**`

---

```
# Fibonacci Series
```




"""

# Learning List
squares = [0,1,4,9,16,25,36]
print(squares)
print(squares[0]) # print view
print(squares[:]) # print view
print(squares[:0:]) # print view
print(squares[:-4]) # print view
print(squares[-4:]) # print view
print(squares+[49,64,81]) # add data to existing list
print(squares[:]) # print view
squares.append(100) # add the data into list
print(squares)
print(len(squares)) # printing the length of list
squares[5]=26
print(squares)
letters = ['a','c', 'd', 'u']
print(letters)
letters[1:3]=['e','i'] # add data into the given place value in list 
print(letters)
letters[1:3]=[]
print(letters)
letters[:]=[]
print(letters)
a = ["Keshav", "Hari", "Sita", "Gita"]
print(a)
b = [1,2,3,4]
print(b)
c = [a,b] # adding list of data into a list
print(c)

# Learning Strings
fName = "Keshav"
space = " "
lname = "Bhandari"
fullName =fName+space+lname # to concatate
print(fullName)
print(fName[3]) # to print the character of given place value 
print(len(fName)) # to get the length of string data
print(fullName[2:6]) # include the begining and exclude the ending place value
data1 = "     Hello       Guys!"
# newData1 = strip(data1)
newData1 = data1.strip() # strop() remove any whitespaces at the begining
print(newData1)
print(fullName.lower()) # lower() make all the letters in lowercase
print(fullName.upper()) # upper() make all the letters in uppercase
print(data1.replace("H", "#H")) # to replace the any letters in a string
print(fullName.split(" "))
skills = "Teaching,Tutoring,Dancing,Singing,Cricket Playing,Programming,Documentation,Photoshop,Event Management,App Development,Software Development,Web Development"
print(skills.split(","))

# Type Casting
x = str(3)    # x will be '3'
print(x)
print(type(x))
y = int(3)    # y will be 3
print(y)
print(type(y))
z = float(3)  # z will be 3.0
print(z)
print(type(z))

# Float Data Type
x = 23.56
y = 12
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)

# Integer Data Type
x = 5
y = 10
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(type(x)) # to get the which type of data is assigned to the variable

# Starting Python
print("Hello World!")