# -*- coding: utf-8 -*-
"""KeshavBhandari_Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pd0vNoIhz606c8P45ZCNVv9ZzeswpYf3
"""

Book :- Author :- Mark Lutz<br>
<br>
Learning Python 5th Edition O'Reilly<br>
Python Cookbook David Beazley O'Reilly<br>
Link:-<br>
<br>
http://www.cs.uni.edu/~fienup/cs051f10/lectures/ <br>
https://github.com/MrAlex6204/Books/blob/master/Learning%20Python%2C%205th%20Edition.pdf <br>
https://github.com/tomarraj008/data_books/blob/master/Python%20Cookbook%2C%203rd%20Edition.pdf <br>

"""First Week Assignment

Test Your Knowledge: Quiz

What are the six main reasons that people choose to use Python?<br>
Name four notable companies or organizations using Python today.<br>
Why might you not want to use Python in an application?<br>
What can you do with Python?<br>
What’s the significance of the Python import this statement?<br>
Why does “spam” show up in so many Python examples in books and on the Web?<br>
What is your favorite color?<br>
Test Your Knowledge: Quiz<br>
<br>
What is the Python interpreter?<br>
What is source code?<br>
What is byte code?<br>
What is the PVM?<br>
Name two or more variations on Python’s standard execution model.<br>
How are CPython, Jython, and IronPython different?<br>
What are Stackless and PyPy?<br>
Test Your Knowledge: Quiz<br>
<br>
How can you start an interactive interpreter session?<br>
Where do you type a system command line to launch a script file?<br>
Name four or more ways to run the code saved in a script file.<br>
Name two pitfalls related to clicking file icons on Windows.<br>
Why might you need to reload a module?<br>
How do you run a script from within IDLE?<br>
Name two pitfalls related to using IDLE.<br>
What is a namespace, and how does it relate to module files?<br>
Test Your Knowledge: Quiz<br>
<br>
Name four of Python’s core data types.<br>
Why are they called “core” data types?<br>
What does “immutable” mean, and which three of Python’s core types are considered immutable?<br>
What does “sequence” mean, and which three types fall into that category?<br>
What does “mapping” mean, and which core type is a mapping?<br>
What is “polymorphism,” and why should you care?<br>

**Projects:-**

1. Open a Python shell, enter the following expressions, and observe the results:<br>
a. 8<br>
b. 8 * 2<br>
c. 8 ** 2<br>
d. 8/12<br>
e. 8 // 12<br>
f. 8/0<br>
"""

8

8*2

8**2

8/12

8//12

8/0

"""2. Write a Python program that prints (displays) your name, address, and telephone number."""

name = input("Enter your name:")
address = input("Enter your address:")
tel = int(input("Enter your telephone number:"))
print("My name is", name)
print("I live in",address)
print("You can contact me at", tel)

"""3. Evaluate the following code at a shell prompt: print("Your name is", name). Then assign name an appropriate value, and evaluate the statement again."""

print("Your name is", name)
name = input("Enter your name:")
print("Your name is", name)

"""4. Write and test a program that accepts the user's name(as text) and age(as a number) as input. The program should output a sentense containing the user's name and age."""

name = str(input("Enter your name:"))
age = int(input("Enter your age:"))
print("Your name is "+name+". Your age is "+str(age)+".")

"""5. Write and test a program that computes the area of a circle. This program should request a number representing  a radius as input from the user. It should use the formula 3.14*radius**2 to compute the area and then output this result suitably labeled."""

Pie = float(3.14)
print("Given\nPie="+str(3.14)+",Radius=?")
radius = float(input("Enter the radius of the circle:"))
mainArea = float(Pie*radius**2)
wrongArea = float(Pie*radius*2)
print("Area of the circle is: ")
print(mainArea)
print("Area of the circle with wrong formula(as given in question) is: ")
print(wrongArea)

"""6. Enter an input statement using the input function at the shll prompt. When the prompt asks you for input, enter a number. Then, attempt to add 1 to that number, observe the results and explain what happened."""

num = int(input("Enter a number:"))
result=num+1
print(result)
# explaination:
# entered number is increased by 1 in result and get printed.

"""7. Enter the expression help() at the shell prompt. Follow the instructions to browse the topics and modules."""

help()

"""8. The tax calculator program of the case study outputs a floating-point number that might show more than two digits of precision. Use the round function to modify the program to display at most two digits of precision in the output number."""

num = float(input("Enter the number:"))
rounded = round(num, 2)
print("Two digits number is", rounded)

"""9. You can calculate the surface area of a cube if you know the length of an edge. Write a program that takes the length of an edge(an integer) as input and prints the cube's surface area as output."""

edgeLength = int(input("Enter the length of an edge:"))
cubeSurfaceArea = 6*edgeLength**2
print("The total surface area of cube is",cubeSurfaceArea,"sq. units.")

"""10.Five Star Retro Video rents VHS tapes and DVDs to the same connoisseurs who like to buy LP record albums. The store rents new videos for $3.00 a night, and oldies for $2.00 a night.

Write a program that the clerks at Five Star Retro Video can use to calculate the total charge for a customer’s video rentals.

The program should prompt the user for the number of each type of video and output the total cost.
"""

new = int(input("Enter the number of new videos:"))
old = int(input("Enter the number of old videos:"))
totalCost = (new *3.00)+(old*2.00)
print("Total cost for the customer is $",totalCost,"only.")

"""11. Write a program that takes the radius of a sphere(a floating point number) as input and then outputs the sphere's diameter, circumference, surface area and volume."""

radius = float(input("Enter the radius of a sphere:"))
Pie = 22/7
diameter = 2*radius
circumference = 2*Pie*radius
surfaceArea = 4*Pie*radius**2
volume = (4/3)*Pie*radius**3
print("Radius of a Sphere is",radius,".\nDiameter of Sphere is",diameter,".\nCircumference of sphere is",circumference,".\nSurface Area of Sphere is",surfaceArea,".\nVolume of Sphere is",volume,".")

"""12. Instructions An object's momentum is its mass multiplied by its velocity. Write a program that accepts an object's mass (in kilograms) and velocity (in meters per second) as inputs, and then outputs its momentum."""

mass = float(input("Enter the mass of an object(in KG):"))
velocity = float(input("Enter the velocity of an object(in m/s):"))
momentum = mass*velocity
print("The momentum(P) of an object having mass",mass,"KG and velocity",velocity,"meters per second is",momentum)

"""13. The kinetic energy of a moving object is given by the formula KE = ½mv2 where m is the object’s mass and v is its velocity.

Modify the program you created in Project 5 so that it prints the object’s kinetic energy as well as its momentum.
"""

m = float(input("Enter the mass of an object(in KG):"))
v = float(input("Enter the velocity of an object(in m/s):"))
momentum = m*v
KE = (1/2)*m*v**2
print("The momentum(P) of an object having mass",m,"KG and velocity",v,"meters per second is",momentum)
print("The Kinetic Energy(KE) of an object having mass",m,"KG and velocity",v,"meters per second is",KE)

"""14. An employee’s total weekly pay equals the hourly wage multiplied by the total number of regular hours plus any overtime pay. Overtime pay equals the total overtime hours multiplied by 1.5 times the hourly wage. Write a program that takes as inputs the hourly wage, total regular hours, and total overtime hours and displays an employee’s total weekly pay."""

hourlyWage = float(input("Enter hourly wage:"))
totalRegularHours = int(input("Enter the total working hours:"))
totalOverTimeHours = int(input("Enter the total overtime hours:"))
weeklyPay = (hourlyWage * totalRegularHours) + (totalOverTimeHours * (1.5 * hourlyWage))
print("The total weekly pay for the employee is", weeklyPay)